namespace: my_own_namespace
name: yandex_cloud_elk
version: 1.0.0
readme: README.md
authors:
  - GlubuchikAr
description: Custom collection with file creation module for Yandex Cloud ELK
license:
  - GPL-3.0-or-later
tags:
  - file
  - creation
  - custom
repository: https://github.com/GlubuchikAr/my_own_collection
documentation: https://github.com/GlubuchikAr/my_own_collection
homepage: https://github.com/GlubuchikAr/my_own_collection
issues: https://github.com/GlubuchikAr/my_own_collection/issues