---
- name: Create file using custom module
  my_own_namespace.yandex_cloud_elk.my_own_module:
    path: "{{ file_path }}"
    content: "{{ file_content }}"
  register: file_result

- name: Show file creation result
  debug:
    var: file_result
